# 老王Python学习笔记
> 运行环境：代码编辑器sublime text 3（配置anaconda，python3.5）
## 二、进阶篇

### 进阶篇15-异常处理1.1

exception，中译异常
> 保守派的圣杯，被滥用的良药。


#### 1.出错代码，他们出了什么错.

出错 = 抛出异常

```
# coding=utf-8

a = [1,2,3,4,5]
print(a[3])
>>> 4
print(a[6])
>>> 代码抛出异常（IndexError: list index out of range），并停止继续运行

```

#### 2.我们不想让他们出错，该怎么办。exception来了。
except确定抛出异常时的执行内容，从而保证代码继续执行下去。
```
# coding=utf-8

a = [1, 2, 3, 4, 5]

try:
    print(a[6])
except:
    print('error')

print('go on')

>>>
error
go on

```

#### 3.基本语法

```
# coding=utf-8

a = [1, 2, 3, 4, 5]

try:
    " 框住了你感觉会抛出异常的代码 "
    print("first step")  # 正常输出
    print(a[6])        # 抛出异常
    print("third step")  # 因为上面抛出异常所以调到except，该行代码不运行

except:
    " try代码块里的代码如果抛出异常，该执行什么内容"
    print(u"sorry it's error")
else:
    "try代码块里的代码没有抛出异常，执行的内容"
    print("go on")
finally:
    "不管如何，finally里的代码，总会执行"
    print("game over")

>>>
first step
sorry it's error
game over

```

#### 4.我们为什么不让他抛出异常？

在开发阶段，我们是可以让任何代码抛出异常。

特别是上线之前，抛出的异常越多，问题暴露越充分，debug上线之后，出现的问题才会更少。

滥用try只会隐藏异常，而不会自动debug 


#### 5.什么时候用，怎么用？

什么时候用异常？ 
> 不得不用的时候。

异常怎么用？

> 1. 明确可能会出现哪些问题，分析问题，得到这些问题会抛出的指定异常。
> 2. 捕获正确的异常，不要直接 try except。
> 3. 异常的处理，要合理。要有日志。

```
import urllib.request

url = "http://wasdasdasd"

try:
    d = urllib.request.urlopen(url)
except IndentationError:  # 第一类异常
    print("缩进异常")
except IOError:           # 第二类异常
    print("输入输出异常")
except SyntaxError:       # 第三类异常
    print("语法异常")
else:
    content = d.read()
finally:
    d.close()

>>> 输入输出异常

```

### 习题

1 定义一个函数func(filename) filename:文件的路径，函数功能：打开文件，并且返回文件内容，最后关闭，用异常来处理可能发生的错误。

```
# coding=utf-8

def func(filename):
    """
    @filename:文件的路径
    @函数功能：打开文件，并且返回文件内容，最后关闭
    @要求：用异常来处理可能发生的错误。
    """
    try:
        f = open(filename, 'r')
    except IndentationError:
        return "缩进异常"
    except IOError:
        return "输入输出异常"
    except UnboundLocalError:
        return '局部变量异常'
    except SyntaxError:
        return "语法异常"
    else:
        content = f.read()
        f.close()
        return content

print(func(r'C:\Program Files\Sublime Text 3\practice\__init__.py'))
>>>
# coding=utf-8

__all__ = ['get_page', 'get_url', 'get_dir', 'get_doc_pydoc']

```
---
2 定义一个函数func(urllist)   urllist:为URL的列表，例如：['http://xx.com','http://www.xx.com','http://www.xxx.com'...] 

函数功能：要求依次打开url，打印url对应的内容，如果有的url打不开，则把url记录到日志文件里，并且跳过继续访问下个url。

```
import urllib.request
import logging

def func2(urllist):
    """
    @urllist:为URL的列表，例如：['http://xx.com','http://www.xx.com','http://www.xxx.com'...]
    @函数功能：要求依次打开url，打印url对应的内容，如果有的url打不开，则把url记录到日志文件里，并且跳过继续访问下个url。
    """
    if not isinstance(urllist, list):
        return '输入参数类型异常'
    for url in urllist:
        try:
            content = urllib.request.urlopen(url)
        except:
            # 配制根记录器（root logger）
            logging.basicConfig(
                filename='url.log', format='%(levelname)-5s %(asctime)s %(message)s', level=logging.ERROR)
            log = logging.getLogger('url')  # 创建logger对象
            log.error(u"webpages can't be open: %s", url)  # 向logger发送ERROR日志消息
        else:
            print('%s: %s' % (url, content.read()))
    return open('url.log', 'r').read()  # 输出日志内容

print(func2(['http://www.baidu.com', 'http://www.abc.com']))
>>> ERROR 2017-05-27 23:36:32,865 webpages can't be open: http://www.abc.com
```
---
3. 定义一个函数func(domainlist)   domainlist:为域名列表，例如：['xx.com','www.xx.com','www.xxx.com'...]
函数功能：要求依次ping 域名，如果ping 域名返回结果为：request time out，则把域名记录到日志文件里，并且跳过继续ping下个域名。（提示用os模块的相关方法）

```
import os
import logging

def func3(domainlist):
    """
    定义一个函数func(domainlist)
    @domainlist:为域名列表，例如：['xx.com','www.xx.com','www.xxx.com'...]
    @功能：要求依次ping 域名，如果ping 域名返回结果为：request time out，
    则把域名记录到日志文件里，并且跳过继续ping下个域名。
    """
    if not isinstance(domainlist, list):
        return '输入参数类型异常'
    for d in domainlist:
        f = os.popen('ping %s' % d)
        result = f.read()
        if '请求超时' not in result:
            print(result)
        else:  
            # 配制根记录器（root logger）
            logging.basicConfig(
                filename='ping.log', format='%(levelname)-5s %(asctime)s %(message)s', level=logging.ERROR)
            log = logging.getLogger('ping')  # 创建logger对象
            log.error(u"request time out: %s", d)  # 向logger发送ERROR日志消息

    return open('ping.log', 'r').read()

print(func3(['www.baidu.com', 'www.xx.com']))
>>>
正在 Ping www.a.shifen.com [119.75.218.70] 具有 32 字节的数据:
来自 119.75.218.70 的回复: 字节=32 时间=3ms TTL=54
来自 119.75.218.70 的回复: 字节=32 时间=3ms TTL=54
来自 119.75.218.70 的回复: 字节=32 时间=3ms TTL=54
来自 119.75.218.70 的回复: 字节=32 时间=3ms TTL=54

119.75.218.70 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 3ms，最长 = 3ms，平均 = 3ms


ERROR 2017-05-28 23:37:09,214 request time out: www.xx.com
```





